name: Update Airbnb iCal (All Listings)

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download all Airbnb iCal feeds
        run: |
          # Start with a clean file
          echo "" > airbnb.ics

          # Listing 1
          curl -L "https://www.airbnb.com/calendar/ical/1355078859895588226.ics?t=ef71f5d189624274a64c20bb197e4be3" >> airbnb.ics
          echo "" >> airbnb.ics

          # Listing 2
          curl -L "https://www.airbnb.com/calendar/ical/1194501603461940563.ics?t=b12407e10b7e445f96394d50ac2a2b0d" >> airbnb.ics
          echo "" >> airbnb.ics

          # Listing 3
          curl -L "https://www.airbnb.com/calendar/ical/1166699194313702494.ics?t=725dc7c40d84486a89e266648d50c1b3" >> airbnb.ics
          echo "" >> airbnb.ics

          # Listing 4
          curl -L "https://www.airbnb.com/calendar/ical/1169542988343878536.ics?t=9de45ac35a1e4ac3849bb5238af21d5f" >> airbnb.ics
          echo "" >> airbnb.ics

          # Listing 5
          curl -L "https://www.airbnb.com/calendar/ical/1193566712390606838.ics?t=8972eb21cdbd4c4b96627cd9d30addaa" >> airbnb.ics
          echo "" >> airbnb.ics

          # Listing 6
          curl -L "https://www.airbnb.com/calendar/ical/1169549533139105227.ics?t=0d298960a8d04a8da17b8ef07fa1486e" >> airbnb.ics
          echo "" >> airbnb.ics

      - name: Commit updated file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add airbnb.ics
          git commit -m "Update merged iCal" || echo "No changes"
          git push
